### ISSUE TITLE
resize issue on Safari 8.02 OSX

### ISSUE THREAD

**Issue by christophercomis** [aekaplan/grid#25]
I am planning on using your grid for responsive site and I have noticed that when I resize the window in Safari 8.02 there is a flickering of the formatting. It occurs from 640px to 755px then stabilizes and begins again at 1150px to 1240px. I've tried to do some troubleshooting but I've been unable to remedy it. It does not happen with Firefox or Chrome. 

Any input you have would be very much appreciated. Thanks for putting together the tutorial to jumpstart responsive design.

--- I isolated the issue. It seemed to be related to the use of percentages to calculate the fonts 
@media (min-width: 40rem) {
  html { font-size: 112%; }
}

@media (min-width: 64rem) {
  html { font-size: 120%; }
}
When I removed this bid of code the problem disappeared.

**Comment by aekaplan** [comment]
Yeah it's a bug in Safari :(
